version: '3'
services:
  api:
    image: vegimag/vegimag-api:latest
    ports:
      - "3211:80"
    volumes:
      - data:/data
  frontend:
    image: vegimag/vegimag-frontend:latest
    ports:
      - "3212:80"

volumes:
  data:
